#!/usr/bin/env node
/**
 * Rename the product, repository-wide, from one constant.
 *
 *   node scripts/rebrand.mjs --name Chisel --dry-run
 *   node scripts/rebrand.mjs --name Chisel
 *   node scripts/rebrand.mjs --name Chisel --scope chisel-tools --repo acme/chisel
 *
 * README.md and the ADRs promise this is a single command, and a promise like that
 * decays quietly: the name spreads into package scopes, binary names, environment
 * variable prefixes, workspace paths, and documentation links, and by the time
 * anyone tries it the answer is a week of grep. So it exists now, while the surface
 * is small enough to get right.
 *
 * Why anyone would run it: the name has had no trademark search
 * (docs/roadmap.md lists that at M8), the npm scope is unclaimed, and a project
 * that cannot be renamed cheaply is a project that ships under a name it was told
 * to stop using.
 *
 * Substitutions are longest-first, so `@adze/` is rewritten as a scope before the
 * bare word `adze` is reached. Getting that order wrong is the whole difficulty:
 * a naive pass turns `@adze/apply` into `@chisel/apply` only by accident, and
 * cannot honour a scope that differs from the lowercase name.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * The current brand. One block, which is the point of the script.
 *
 * These values are rewritten by the script when it runs on itself, so after a
 * rebrand this block describes the new brand and a second run is a no-op. That is
 * correct rather than clever: the file is a description of what the product is
 * currently called.
 */
const BRAND = {
  /** Display name, as written in prose. */
  name: 'Adze',
  /** Lowercase identifier: the binary, the log prefix, the directory names. */
  slug: 'adze',
  /** npm scope, without the leading `@`. */
  scope: 'adze',
  /** Environment variable prefix. */
  envPrefix: 'ADZE_',
  /** `owner/repo` on GitHub. */
  repo: 'AyanB123/adze',
};

const SKIP_DIRS = new Set([
  'node_modules',
  '.git',
  'dist',
  'out',
  'build',
  'coverage',
  '.turbo',
  '.vite',
  '.runs',
  '.pnpm-store',
  'generated',
]);

/**
 * Files that are rewritten by their own tooling rather than by hand.
 *
 * `pnpm-lock.yaml` in particular: editing it textually produces a lockfile that
 * disagrees with the registry. It is regenerated by `pnpm install`, which the
 * summary says.
 */
const SKIP_FILES = new Set(['pnpm-lock.yaml', 'package-lock.json', 'yarn.lock']);

const BINARY_EXTENSIONS = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.icns',
  '.pdf',
  '.woff',
  '.woff2',
  '.ttf',
  '.otf',
  '.eot',
  '.zip',
  '.gz',
  '.tgz',
  '.br',
  '.7z',
  '.xz',
  '.wasm',
  '.node',
  '.exe',
  '.dll',
  '.dylib',
  '.so',
  '.mp4',
  '.webm',
  '.mp3',
  '.wav',
]);

function parseArgs(argv) {
  const out = { dryRun: false, json: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--dry-run') out.dryRun = true;
    else if (arg === '--json') out.json = true;
    else if (arg === '-h' || arg === '--help') out.help = true;
    else if (arg === '--name' || arg === '--scope' || arg === '--repo' || arg === '--slug') {
      const value = argv[++i];
      if (value === undefined) {
        process.stderr.write(`rebrand: ${arg} requires a value\n`);
        process.exit(2);
      }
      out[arg.slice(2)] = value;
    } else {
      process.stderr.write(`rebrand: unknown option ${arg}\n`);
      process.exit(2);
    }
  }
  return out;
}

const USAGE = `rebrand — rename the product repository-wide

Usage:
  node scripts/rebrand.mjs --name <NewName> [options]

Options:
  --name <NewName>     new display name (required). Everything else is derived.
  --slug <newname>     lowercase identifier. Default: --name lowercased.
  --scope <scope>      npm scope without '@'. Default: the slug.
  --repo <owner/repo>  GitHub slug. Default: the current owner with the new slug.
  --dry-run            report what would change and write nothing
  --json               machine-readable output
  -h, --help           this message

Currently branded as: ${BRAND.name} (slug '${BRAND.slug}', scope '@${BRAND.scope}', repo '${BRAND.repo}')
`;

const args = parseArgs(process.argv.slice(2));

if (args.help === true) {
  process.stdout.write(USAGE);
  process.exit(0);
}
if (args.name === undefined) {
  process.stderr.write(`rebrand: --name is required\n\n${USAGE}`);
  process.exit(2);
}

const target = {
  name: args.name,
  slug: args.slug ?? args.name.toLowerCase().replace(/[^a-z0-9-]+/g, '-'),
  scope: undefined,
  envPrefix: undefined,
  repo: undefined,
};
target.scope = args.scope ?? target.slug;
target.envPrefix = `${target.slug.toUpperCase().replace(/-/g, '_')}_`;
target.repo = args.repo ?? `${BRAND.repo.split('/')[0]}/${target.slug}`;

/**
 * Ordered longest-first. `@adze/` must be handled before `adze`, and `ADZE_` before
 * `Adze`, or a later rule consumes the text a more specific rule needed.
 */
const RULES = [
  { label: 'npm scope', from: `@${BRAND.scope}/`, to: `@${target.scope}/` },
  { label: 'repo slug', from: BRAND.repo, to: target.repo },
  { label: 'env prefix', from: BRAND.envPrefix, to: target.envPrefix },
  { label: 'display name', from: BRAND.name, to: target.name },
  { label: 'slug', from: BRAND.slug, to: target.slug },
];

function isTextFile(path) {
  if (BINARY_EXTENSIONS.has(extname(path).toLowerCase())) return false;
  try {
    // A NUL byte in the first 8 KiB is the standard heuristic, and it is right often
    // enough that guessing from the extension alone is not worth the risk of
    // corrupting a binary the extension list did not anticipate.
    const buffer = readFileSync(path);
    const head = buffer.subarray(0, Math.min(8192, buffer.length));
    return !head.includes(0);
  } catch {
    return false;
  }
}

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    let stats;
    try {
      stats = statSync(full);
    } catch {
      continue;
    }
    if (stats.isDirectory()) {
      if (SKIP_DIRS.has(entry)) continue;
      yield* walk(full);
    } else if (stats.isFile()) {
      if (SKIP_FILES.has(entry)) continue;
      yield full;
    }
  }
}

function countOccurrences(text, needle) {
  if (needle.length === 0) return 0;
  let count = 0;
  let from = 0;
  for (;;) {
    const at = text.indexOf(needle, from);
    if (at === -1) break;
    count++;
    from = at + needle.length;
  }
  return count;
}

const changed = [];
const perRule = Object.fromEntries(RULES.map((r) => [r.label, 0]));
let scanned = 0;

for (const file of walk(repoRoot)) {
  if (!isTextFile(file)) continue;
  scanned++;

  let text;
  try {
    text = readFileSync(file, 'utf8');
  } catch {
    continue;
  }

  let next = text;
  const hits = {};
  for (const rule of RULES) {
    const count = countOccurrences(next, rule.from);
    if (count === 0) continue;
    hits[rule.label] = count;
    perRule[rule.label] += count;
    next = next.replaceAll(rule.from, rule.to);
  }

  if (next === text) continue;
  changed.push({
    path: relative(repoRoot, file).split(sep).join('/'),
    replacements: hits,
    total: Object.values(hits).reduce((a, b) => a + b, 0),
  });
  if (!args.dryRun) writeFileSync(file, next, 'utf8');
}

/** Paths that carry the old name and must be moved by hand. */
const pathsToRename = [];
for (const file of walk(repoRoot)) {
  const rel = relative(repoRoot, file).split(sep).join('/');
  if (rel.toLowerCase().includes(BRAND.slug.toLowerCase())) pathsToRename.push(rel);
}

const followUp = [
  'pnpm install    regenerate pnpm-lock.yaml; it is not edited textually',
  'pnpm check      lint, typecheck, and test the renamed tree',
  `verify the npm scope '@${target.scope}' is unclaimed before publishing`,
  `verify the GitHub repository '${target.repo}' exists, or update --repo`,
  'run a trademark search on the new name before announcing it (docs/roadmap.md M8)',
];

if (args.json) {
  process.stdout.write(
    `${JSON.stringify(
      {
        dryRun: args.dryRun,
        from: BRAND,
        to: target,
        rules: RULES.map((r) => ({
          label: r.label,
          from: r.from,
          to: r.to,
          count: perRule[r.label],
        })),
        scanned,
        filesChanged: changed.length,
        totalReplacements: Object.values(perRule).reduce((a, b) => a + b, 0),
        changed,
        pathsToRename,
        followUp,
      },
      null,
      2,
    )}\n`,
  );
} else {
  process.stdout.write(
    `${args.dryRun ? 'Dry run — nothing written.' : 'Rebranded.'}\n\n` +
      `  ${BRAND.name} -> ${target.name}\n` +
      `  @${BRAND.scope}/ -> @${target.scope}/\n` +
      `  ${BRAND.slug} -> ${target.slug}\n` +
      `  ${BRAND.envPrefix} -> ${target.envPrefix}\n` +
      `  ${BRAND.repo} -> ${target.repo}\n\n`,
  );

  for (const rule of RULES) {
    process.stdout.write(`  ${rule.label.padEnd(14)} ${String(perRule[rule.label]).padStart(5)}\n`);
  }
  process.stdout.write(`\nScanned ${scanned} text file(s); ${changed.length} would change.\n\n`);

  for (const file of changed.slice(0, 40)) {
    process.stdout.write(`  ${String(file.total).padStart(4)}  ${file.path}\n`);
  }
  if (changed.length > 40) {
    process.stdout.write(`  ... and ${changed.length - 40} more\n`);
  }

  if (pathsToRename.length > 0) {
    // Deliberately not renamed automatically. Moving a file changes import
    // specifiers and git history in ways a text substitution cannot reason about,
    // and doing it silently is how a rebrand becomes a debugging session.
    process.stdout.write(
      `\n${pathsToRename.length} path(s) contain '${BRAND.slug}' and must be moved by hand:\n`,
    );
    for (const p of pathsToRename.slice(0, 20)) process.stdout.write(`  ${p}\n`);
  }

  process.stdout.write('\nThen:\n');
  for (const step of followUp) process.stdout.write(`  ${step}\n`);
}
