#!/usr/bin/env bash
# 00-preflight.sh — check the host before anything expensive starts.
#
# The Code-OSS build takes tens of minutes. Every condition below is one that
# produces a failure late, in a form that does not name its own cause: a
# CRLF-mangled patch reports "patch does not apply", a MAX_PATH overrun reports a
# missing module, and a missing Spectre-mitigated MSVC library reports a linker
# error inside a transitive dependency nobody has heard of.
#
# So this collects every problem and reports them together, rather than exiting
# on the first one. A maintainer fixing four things in one pass is the whole
# point.
#
# Exits non-zero if any hard requirement is unmet. Warnings do not fail.
set -euo pipefail

_here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../config.sh
. "${_here}/../config.sh"
# shellcheck source=./lib.sh
. "${_here}/lib.sh"

require_bash

problems=0
fail() {
  err "$*"
  problems=$((problems + 1))
}

step "preflight"

# ─── Required tools ────────────────────────────────────────────────────────

have git || fail "git is not on PATH."
have jq || fail "jq is not on PATH. product.json is generated by a jq program (apps/ide/branding/product.delta.jq); there is no committed copy to fall back to."
have node || fail "node is not on PATH. Node 22.12+ is required."
have python3 || have python || warn "no python found. Upstream's native modules build through node-gyp, which requires Python 3."

if have rg; then
  dim "ripgrep $(rg --version | head -n1 | awk '{print $2}')"
else
  warn "ripgrep is not on PATH. 50-neutralize-telemetry.sh needs it; grep -r is not a substitute because the sweep relies on rg's ignore handling to avoid rewriting node_modules."
fi

if have node; then
  node_major="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
  if [ "$node_major" -lt 22 ]; then
    fail "node $(node -v) is too old. Upstream requires Node 22+ and the build fails in ways that look unrelated on older majors."
  else
    dim "node $(node -v)"
  fi
fi

if have jq; then
  dim "jq $(jq --version)"
fi

# ─── Configuration ─────────────────────────────────────────────────────────

if [ -z "$ADZE_UPSTREAM_TAG" ]; then
  fail "apps/ide/UPSTREAM_TAG is missing or empty. The upstream pin lives there and nowhere else."
elif ! printf '%s' "$ADZE_UPSTREAM_TAG" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  fail "apps/ide/UPSTREAM_TAG contains '$ADZE_UPSTREAM_TAG', which is not an X.Y.Z release tag. Building from a branch is explicitly rejected by ADR-0010: a moving target makes a patch failure impossible to bisect."
else
  dim "upstream pin $ADZE_UPSTREAM_TAG"
fi

[ -f "$ADZE_PRODUCT_DELTA" ] || fail "missing $ADZE_PRODUCT_DELTA"
[ -f "$ADZE_GALLERY_NAMESPACES" ] || fail "missing $ADZE_GALLERY_NAMESPACES"
[ -d "$ADZE_PATCH_DIR" ] || fail "missing $ADZE_PATCH_DIR"
[ -f "$ADZE_GALLERY_AUDIT" ] || fail "missing $ADZE_GALLERY_AUDIT (owned by scripts/, wired to from here)"

# ─── Line endings ──────────────────────────────────────────────────────────
#
# The single most common Windows-only fork build failure. A patch checked out
# with CRLF fails `git apply` with "patch does not apply" and gives no hint that
# the content is fine and only the line endings are wrong. .gitattributes marks
# *.patch as -text to prevent it; this verifies the checkout actually honoured
# that, because a repository cloned before the attribute was added keeps the
# normalised copies.
step "line endings"

crlf_found=0
while IFS= read -r patch; do
  [ -n "$patch" ] || continue
  if LC_ALL=C grep -qU $'\r' "$patch" 2>/dev/null; then
    fail "$patch contains CRLF. It will fail to apply. Fix with: git rm --cached -r apps/ide/patches && git checkout -- apps/ide/patches"
    crlf_found=1
  fi
done <<EOF
$(find "$ADZE_PATCH_DIR" -type f \( -name '*.patch' -o -name '*.patch.no' \) 2>/dev/null | sort)
EOF

if [ "$crlf_found" -eq 0 ]; then
  dim "patch series is LF-clean"
fi

for script in "${_here}"/*.sh "${ADZE_IDE_DIR}/config.sh"; do
  if LC_ALL=C grep -qU $'\r' "$script" 2>/dev/null; then
    fail "$script contains CRLF. Git Bash tolerates it; the Code-OSS build scripts that invoke it do not."
  fi
done

# ─── Windows-specific ──────────────────────────────────────────────────────

if is_windows_bash; then
  step "windows checks"

  # Upstream's node_modules tree nests deeply enough that a build root more than
  # roughly 30 characters deep overruns MAX_PATH (260) in whichever dependency
  # happens to have the longest path this week. The failure surfaces as
  # ENAMETOOLONG or as a module that "does not exist".
  build_root_len=${#ADZE_IDE_BUILD_ROOT}
  if [ "$build_root_len" -gt 32 ]; then
    warn "build root is $build_root_len characters: $ADZE_IDE_BUILD_ROOT"
    info "Windows caps most path APIs at 260 characters and upstream's node_modules"
    info "tree consumes over 200. Prefer a short root:"
    info "    ADZE_IDE_BUILD_ROOT=/c/a bash apps/ide/scripts/build.sh"
  fi

  if have git; then
    longpaths="$(git config --get core.longpaths || echo false)"
    if [ "$longpaths" != "true" ]; then
      warn "core.longpaths is not enabled. Enable it for this clone: git config core.longpaths true"
    fi
  fi

  autocrlf="$(git config --get core.autocrlf || echo unset)"
  if [ "$autocrlf" = "true" ]; then
    warn "core.autocrlf=true. .gitattributes overrides it for *.patch and *.sh, but a stale index can keep normalised copies. If a patch fails to apply, re-checkout apps/ide/patches first."
  fi

  info "Two more Windows failure modes cannot be detected from here and are"
  info "documented in apps/ide/README.md: MSVC Spectre-mitigated libraries are a"
  info "separate Visual Studio Installer component that node-gyp needs, and"
  info "real-time antivirus scanning locks files mid-build and surfaces as EBUSY."
fi

# ─── Disk ──────────────────────────────────────────────────────────────────

if have df; then
  avail_kb="$(df -Pk "$(dirname -- "$ADZE_IDE_BUILD_ROOT")" 2>/dev/null | awk 'NR==2 {print $4}' || echo '')"
  if [ -n "$avail_kb" ] && [ "$avail_kb" -lt 20971520 ]; then
    warn "under 20 GB free at $(dirname -- "$ADZE_IDE_BUILD_ROOT"). A checkout plus node_modules plus six packaged targets does not fit in less."
  fi
fi

# ─── Verdict ───────────────────────────────────────────────────────────────

if [ "$problems" -gt 0 ]; then
  log ""
  die "$problems preflight problem(s). Nothing was fetched or built."
fi

step "preflight passed"
info "Nothing has been fetched, patched, or built yet — that is 10-fetch-upstream.sh onward."
