#!/usr/bin/env bash
# 30-generate-product.sh — write product.json from the jq delta.
#
# ADR-0010 calls this the highest-value single decision in the fork strategy, and
# the reasoning is in apps/ide/branding/product.delta.jq. In one line: upstream's
# product.json took 29 commits in 5.8 months, so a fork that stores a merged copy
# conflicts on it at nearly every release, and the correct resolution is always
# "keep all of theirs and all of ours" — which is exactly what a textual merge
# cannot express. Storing the delta turns that recurring merge into this script.
#
# Usage:
#   bash apps/ide/scripts/30-generate-product.sh [--print] [--allow-placeholders]
#
#   --print               Write the generated document to stdout instead of to the
#                         checkout. Nothing is modified.
#   --allow-placeholders  Permit reserved-TLD endpoints in the output. Equivalent
#                         to ADZE_ALLOW_PLACEHOLDER_ENDPOINTS=1.
set -euo pipefail

_here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../config.sh
. "${_here}/../config.sh"
# shellcheck source=./lib.sh
. "${_here}/lib.sh"

require_bash
require_cmd jq "product.json has no committed copy — it is generated by ${ADZE_PRODUCT_DELTA}."

print_only=0
while [ $# -gt 0 ]; do
  case "$1" in
    --print) print_only=1 ;;
    --allow-placeholders) ADZE_ALLOW_PLACEHOLDER_ENDPOINTS=1 ;;
    -h | --help)
      sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) die "unknown argument: $1" ;;
  esac
  shift
done

[ -f "$ADZE_PRODUCT_DELTA" ] || die "missing delta program: $ADZE_PRODUCT_DELTA"

# The input is whichever product.json upstream currently ships. Reading it from
# the checkout rather than from a committed copy is the entire point: upstream's
# new keys arrive on their own and our overrides are re-applied on top.
upstream_product="${ADZE_IDE_BUILD_ROOT}/product.json"
[ -f "$upstream_product" ] ||
  die "no upstream product.json at $upstream_product. Run 10-fetch-upstream.sh first."

step "generating product.json"
info "delta  $(basename -- "$ADZE_PRODUCT_DELTA")"
info "input  $upstream_product"

# -S sorts keys. Byte-stable output across runs keeps the diff in a merge-bot pull
# request reviewable instead of being reordered noise.
generated="$(jq -S -f "$ADZE_PRODUCT_DELTA" "$upstream_product")" ||
  die "the jq delta failed. Check it with: jq -n -f $ADZE_PRODUCT_DELTA"

printf '%s' "$generated" | jq -e 'type == "object"' >/dev/null ||
  die "the delta did not produce a JSON object."

# ─── Assertions on the output ──────────────────────────────────────────────
#
# These are properties the fork's correctness depends on, checked on the real
# generated file rather than trusted because the delta looked right in review.

assert_fail=0
assert() {
  local label="$1" filter="$2"
  if printf '%s' "$generated" | jq -e "$filter" >/dev/null 2>&1; then
    dim "ok  $label"
  else
    err "FAIL $label"
    assert_fail=$((assert_fail + 1))
  fi
}

step "checking the generated document"

assert "applicationName is not upstream's" '.applicationName | . != "code" and . != "code-oss"'
assert "dataFolderName is not upstream's" '.dataFolderName | . != ".vscode" and . != ".vscode-oss"'
assert "telemetry endpoint keys are absent" \
  'has("aiConfig") == false and has("appCenter") == false and has("tasConfig") == false'
assert "gallery is not the Microsoft Marketplace" \
  '(.extensionsGallery.serviceUrl // "") | test("marketplace\\.visualstudio\\.com") | not'
assert "recommendation map shapes are preserved" \
  '(.languageExtensionTips | type == "array") and (.configBasedExtensionTips | type == "object")'
assert "builtInExtensions no longer pulls from the Marketplace" '.builtInExtensions == []'

# Four distinct AppIds, none of them upstream's. A shared AppId makes our
# installer an upgrade of the user's real VS Code rather than a separate product,
# which is the single most destructive branding mistake available to a fork.
assert "four win32 AppIds are present" \
  'has("win32x64AppId") and has("win32arm64AppId") and has("win32x64UserAppId") and has("win32arm64UserAppId")'
assert "the four AppIds are distinct" \
  '[.win32x64AppId, .win32arm64AppId, .win32x64UserAppId, .win32arm64UserAppId] | (unique | length) == 4'
assert "AppIds keep Inno Setup's doubled-brace escaping" \
  '[.win32x64AppId, .win32arm64AppId, .win32x64UserAppId, .win32arm64UserAppId]
   | all(test("^\\{\\{[0-9A-F-]{36}\\}\\}$"))'
# Upstream's published Code-OSS AppIds. Listed so that copying them back in is a
# build failure rather than something noticed after an installer has shipped.
assert "AppIds are not upstream's" \
  '[.win32x64AppId, .win32arm64AppId, .win32x64UserAppId, .win32arm64UserAppId]
   | any(. as $id | ["{{EA457B21-F73E-494C-ACAB-524FDE069978}}",
                     "{{D1ACE434-89C5-48D1-88D3-E2991DF85475}}",
                     "{{771FD6B0-FA20-440A-A002-3B3BAC16DC50}}",
                     "{{D9E514E7-1A56-452D-9337-2990C0DC4310}}"] | index($id) != null) | not'
assert "win32 mutex and registry identity differ from upstream" \
  '(.win32MutexName != "vscode" and .win32MutexName != "vscodeoss")
   and (.win32RegValueName != "Code" and .win32RegValueName != "CodeOSS")
   and (.win32AppUserModelId | startswith("Microsoft.") | not)'

if [ "$assert_fail" -gt 0 ]; then
  die "$assert_fail assertion(s) failed on the generated product.json. Nothing was written."
fi

# ─── Placeholder endpoints ─────────────────────────────────────────────────
#
# The delta ships hostnames under RFC 2606 reserved TLDs because no gallery,
# update feed, or documentation site has been deployed. A build whose auto-updater
# points at a hostname nobody owns is worse than no build, so this refuses by
# default. It is also the mechanism that makes "no binary has been produced" a
# property of the pipeline rather than a claim in a README.
placeholders="$(printf '%s' "$generated" |
  jq -r '[paths(type == "string") as $p | {path: ($p | join(".")), value: getpath($p)}]
         | map(select(.value | test("://[^/\"]*\\.(example|invalid|test|localhost)(/|$)")))
         | .[] | "\(.path) = \(.value)"')"

if [ -n "$placeholders" ]; then
  if [ "$ADZE_ALLOW_PLACEHOLDER_ENDPOINTS" = "1" ]; then
    warn "placeholder endpoints present, permitted by ADZE_ALLOW_PLACEHOLDER_ENDPOINTS=1:"
    printf '%s\n' "$placeholders" | while IFS= read -r line; do dim "$line"; done
    warn "This build is for local inspection only. Do not distribute it."
  else
    err "the generated product.json still contains placeholder endpoints:"
    log ""
    printf '%s\n' "$placeholders" | while IFS= read -r line; do err "    $line"; done
    log ""
    err "These are reserved TLDs from RFC 2606. Every one has to be replaced with a"
    err "real endpoint in ${ADZE_PRODUCT_DELTA#"${ADZE_REPO_ROOT}/"} before a build is distributable:"
    err ""
    err "  * the gallery needs a self-hosted Open VSX instance (ADR-0009 rejected"
    err "    depending on open-vsx.org directly, and self-hosting is Postgres +"
    err "    Elasticsearch + Redis + object storage)"
    err "  * the update feed needs static JSON behind a CDN (ADR-0010)"
    err ""
    err "To generate anyway for local inspection:"
    err "    ADZE_ALLOW_PLACEHOLDER_ENDPOINTS=1 bash ${BASH_SOURCE[0]#"${ADZE_REPO_ROOT}/"}"
    exit 1
  fi
fi

# ─── Write ─────────────────────────────────────────────────────────────────

if [ "$print_only" -eq 1 ]; then
  printf '%s\n' "$generated"
  exit 0
fi

printf '%s\n' "$generated" >"${upstream_product}.next"
mv -f -- "${upstream_product}.next" "$upstream_product"

step "wrote $upstream_product"
info "$(printf '%s' "$generated" | jq 'keys | length') keys, $(printf '%s\n' "$generated" | wc -l | tr -d ' ') lines"
info "Never committed: apps/ide/vscode/ is gitignored, and this file is regenerated"
info "from the delta on every build."
